REPO_ROOT = File.expand_path((File.dirname(__FILE__))).to_s

require_relative "ruby/RubyUtils.rb"


##  UTILITY TASKS

desc "Removes the Builds directory generated by running config"
task :clean do
	Clean.run
end

desc "Updates all git submodules to the latest commit on their main branch"
task :uth => [:clean] do 
	Git.uth
end

desc "Runs clang-format over all source code"
task :format do
	ClangFormat.run
end


desc "Runs CMake configuration"
task :config, [:mode] do |t, args|
	args.with_defaults(:mode => DEFAULT_BUILD_CONFIG)
	CMake.configure(BuildMode.parse(args.mode))
	DefaultRepoFiles.run
end



namespace :build do

	desc "Builds all apps, and all formats of all plugins"
	task :all, [:mode] do |t, args|
		args.with_defaults(:mode => DEFAULT_BUILD_CONFIG)
		Log.delete_build_log
		CMake.build_all(BuildMode.parse(args.mode))
	end

	desc "Builds all plugins"
	task :plugins, [:mode] do |t, args|
		args.with_defaults(:mode => DEFAULT_BUILD_CONFIG)
		Log.delete_build_log
		CMake.build_target(BuildMode.parse(args.mode), "ALL_PLUGINS")
	end

	desc "Builds all apps"
	task :apps, [:mode] do |t, args|
		args.with_defaults(:mode => DEFAULT_BUILD_CONFIG)
		Log.delete_build_log
		CMake.build_target(BuildMode.parse(args.mode), "ALL_APPS")
	end


	desc "Builds Imogen"
	task :imogen, [:mode, :formats] do |t, args|
		args.with_defaults(:mode => DEFAULT_BUILD_CONFIG)
		Log.delete_build_log
		CMake.build_plugin("Imogen", BuildMode.parse(args.mode), args.formats, args.extras)
	end

	desc "Builds Kicklab"
	task :kicklab, [:mode, :formats] do |t, args|
		args.with_defaults(:mode => DEFAULT_BUILD_CONFIG)
		Log.delete_build_log
		CMake.build_plugin("Kicklab", BuildMode.parse(args.mode), args.formats, args.extras)
	end


	desc "Builds ImogenRemote"
	task :imogen_remote, [:mode] do |t, args|
		args.with_defaults(:mode => DEFAULT_BUILD_CONFIG)
		Log.delete_build_log
		CMake.build_target("ImogenRemote", BuildMode.parse(args.mode))
	end
end


desc "Runs CPack to create installers"
task :pack, [:mode] do |t, args|
	args.with_defaults(:mode => DEFAULT_BUILD_CONFIG)
	CPack.run(BuildMode.parse(args.mode))
end
