require_relative "rake/RakeUtils.rb"


default_config = "debug"


##  UTILITY TASKS

desc "Removes the Builds directory generated by running config"
task :clean do
	FileAide.clean()
end

desc "Runs clang-format over all source code"
task :cf do
	ClangFormat.run()
end

desc "Updates all git submodules to the latest commit on their main branch"
task :uth do 
	Git.uth()
end


##  CONFIGURATION TASKS

desc "Runs CMake configuration"
task :config, [:mode] do |t, args|
	args.with_defaults(:mode => default_config)
	Git.pull_dev_workspace()
	CMake.configure(args.mode)
end

desc "Initializes this workspace"
task :init => [:clean, :uth] do 
	Init.init()
	Rake::Task["config"].invoke
end


##  BUILD TASKS

namespace :build do 

	desc "Builds all apps, and all formats of all plugins"
	task :all, [:mode] => ["rake:config"] do |t, args|
		args.with_defaults(:mode => default_config)
		CMake.build_all(args.mode)
	end

	#  Plugins

	desc "Builds Imogen"
	task :imogen, [:mode, :formats] => ["rake:config"] do |t, args|
		args.with_defaults(:mode => default_config)
		CMake.build_plugin_target("Imogen", args.mode, args.formats, args.extras)
	end

	desc "Builds Kicklab"
	task :kicklab, [:mode, :formats] => ["rake:config"] do |t, args|
		args.with_defaults(:mode => default_config)
		CMake.build_plugin_target("Kicklab", args.mode, args.formats, args.extras)
	end

	#  Apps

	desc "Builds ImogenRemote"
	task :imogen_remote, [:mode] => ["rake:config"] do |t, args|
		args.with_defaults(:mode => default_config)
		CMake.build_app_target("ImogenRemote", args.mode)
	end

	desc "Builds StageHand"
	task :stagehand, [:mode, :formats] => ["rake:config"] do |t, args|
		args.with_defaults(:mode => default_config)
		CMake.build_app_target("StageHand", args.mode)
	end
end

