require_relative "rake/RakeUtils.rb"


default_config = "Debug"


##  UTILITY TASKS

desc "Removes the Builds directory generated by running config"
task :clean do
	Clean.run
end

desc "Runs clang-format over all source code"
task :cf do
	ClangFormat.run
end

desc "Configures default repo scripts"
task :repos do
	PostConfig.run
end

desc "Runs all formatting tasks"
task :format => [:repos, :cf]

desc "Updates all git submodules to the latest commit on their main branch"
task :uth => [:clean] do 
	Git.uth
end


##  CONFIGURATION TASKS

desc "Runs CMake configuration"
task :config, [:mode] do |t, args|
	args.with_defaults(:mode => default_config)
	CMake.configure(args.mode.capitalize)
end

desc "Initializes this workspace"
task :init => [:clean, :uth, :repos] do 
	Init.init
end


##  BUILD TASKS

namespace :build do 

	desc "Builds all apps, and all formats of all plugins"
	task :all, [:mode] => ["rake:config"] do |t, args|
		args.with_defaults(:mode => default_config)
		CMake.build_all(args.mode.capitalize)
	end

	#  Plugins

	desc "Builds Imogen"
	task :imogen, [:mode, :formats] => ["rake:config"] do |t, args|
		args.with_defaults(:mode => default_config)
		CMake.build_plugin_target("Imogen", args.mode.capitalize, args.formats, args.extras)
	end

	desc "Builds Kicklab"
	task :kicklab, [:mode, :formats] => ["rake:config"] do |t, args|
		args.with_defaults(:mode => default_config)
		CMake.build_plugin_target("Kicklab", args.mode.capitalize, args.formats, args.extras)
	end

	#  Apps

	desc "Builds ImogenRemote"
	task :imogen_remote, [:mode] => ["rake:config"] do |t, args|
		args.with_defaults(:mode => default_config)
		CMake.build_app_target("ImogenRemote", args.mode.capitalize)
	end

	desc "Builds StageHand"
	task :stagehand, [:mode, :formats] => ["rake:config"] do |t, args|
		args.with_defaults(:mode => default_config)
		CMake.build_app_target("StageHand", args.mode.capitalize)
	end
end

